Set up the assignment
durdonadev/html pull request #1
Opened 2023-04-23 21:22 UTC by durdonadev

2023-04-23 22:10 UTC, aliramazon commented
Overal, 3 commits is good.

2023-04-23 23:04 UTC, aliramazon requested changes

2023-04-23 23:04 UTC, aliramazon commented on assignments/assignment-8/index.html
> +            <label for="full-name-input">Full Name:</label><br />
bad, useCamelCase

2023-04-23 23:04 UTC, aliramazon commented on assignments/assignment-8/index.html
> +            <label for="full-name-input">Full Name:</label><br />
I understand you used br after label. But, you should not be after input. Div can be used to wrap Input and Label. Like, <div>  Label, br, Input </div>

2023-04-23 23:04 UTC, aliramazon commented on assignments/assignment-8/index.html
> +                accept="image/jpeg, image/jpg, image/webp"
I liked it,

2023-04-23 23:04 UTC, aliramazon commented on assignments/assignment-8/index.html
> +                id="checkboxInput"
There can be multiple checkboxes. So, best one is to use contestCheckboxInput.

2023-04-23 23:04 UTC, aliramazon commented on assignments/assignment-8/index.html
> +            <select name="country" id="countrySelect">
not consistent with Id selection. here used camelCase

2023-04-23 23:04 UTC, aliramazon commented on assignments/assignment-8/index.html
> +            ><br />
for now, each Select should be wrapped in div

2023-04-23 23:04 UTC, aliramazon commented on assignments/assignment-8/index.html
> +                id="description"
descriptionTextarea

2023-04-23 23:04 UTC, aliramazon commented on assignments/assignment-8/index.html
> +            ></textarea>
required

2023-04-23 23:31 UTC, durdonadev commented on assignments/assignment-8/index.html
> +            <select name="country" id="countrySelect">
I used "countrySelect" as camalCase for id. I didn't catch what you mention, sorry?

2023-04-24 18:53 UTC, aliramazon commented
Approved it.

2023-04-24 18:54 UTC, aliramazon approved these changes

2023-04-24 18:59 UTC, aliramazon approved these changes

2023-04-24 23:57 UTC, merged